image: debian:testing-slim

pages:
  script:
  - apt update
  - apt install -y libboost-all-dev libboost-dev python3-pip doxygen fig2dev
  - pip3 install --requirement docs/requirements.txt 
  - cd docs
  - sphinx-build -M html source/ build/
  - mv build/html ../public
  artifacts:
    paths:
    - public
  only:
  - master

tests:
  script:
  - apt update
  - apt install -y libboost-all-dev libboost-dev cmake chrpath default-jdk valgrind gfortran
  - cmake -Denable_model-checking=ON  -Denable_documentation=OFF -Denable_coverage=ON -Denable_java=ON -Denable_lua=OFF -Denable_compile_optimizations=ON -Denable_smpi=ON -Denable_smpi_MPICH3_testsuite=ON -Denable_compile_warnings=ON .
  - make VERBOSE=1 && ctest --output-on-failure
