image: debian:testing-slim

.build: &build
  script:
  - apt-get update
  - apt-get install -y python3-pip cmake doxygen libboost-all-dev libboost-dev fig2dev
  - pip3 install exhale sphinx breathe sphinx_rtd_theme
  - cmake -Denable_documentation=ON .
  - make documentation
  - mkdir docs/doxyoutput
  - mv doc/xml docs/doxyoutput
  - cd docs
  - sphinx-build -M html source/ build/
  - mv build/html ../public
  artifacts:
    paths:
    - public

pages:
  <<: *build
  only:
  - master

test:
  <<: *build
  except:
  - master
